title: sakura
description: "a floral jeklly theme"
encoding: utf-8

exclude: ["README.md", "LICENSE", "*.gem", "*.gemspec", "Gemfile.lock"]

enable_dark_theme: true

footer: "(c) 2025 <a href='https://sporeball.dev' ›sporeball‹/a> &mdash; MIT license"